[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npx --yes tsx prisma/seed-all.ts && npx --yes tsx prisma/seed-characters.ts && npm start"
